In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv('spambase_csv.csv')
df.head()

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,char_freq_%3B,char_freq_%28,char_freq_%5B,char_freq_%21,char_freq_%24,char_freq_%23,capital_run_length_average,capital_run_length_longest,capital_run_length_total,class
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.00,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.00,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.01,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.00,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1


In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4601 entries, 0 to 4600
Data columns (total 58 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   word_freq_make              4601 non-null   float64
 1   word_freq_address           4601 non-null   float64
 2   word_freq_all               4601 non-null   float64
 3   word_freq_3d                4601 non-null   float64
 4   word_freq_our               4601 non-null   float64
 5   word_freq_over              4601 non-null   float64
 6   word_freq_remove            4601 non-null   float64
 7   word_freq_internet          4601 non-null   float64
 8   word_freq_order             4601 non-null   float64
 9   word_freq_mail              4601 non-null   float64
 10  word_freq_receive           4601 non-null   float64
 11  word_freq_will              4601 non-null   float64
 12  word_freq_people            4601 non-null   float64
 13  word_freq_report            4601 

In [6]:
df.isnull().sum()

word_freq_make                0
word_freq_address             0
word_freq_all                 0
word_freq_3d                  0
word_freq_our                 0
word_freq_over                0
word_freq_remove              0
word_freq_internet            0
word_freq_order               0
word_freq_mail                0
word_freq_receive             0
word_freq_will                0
word_freq_people              0
word_freq_report              0
word_freq_addresses           0
word_freq_free                0
word_freq_business            0
word_freq_email               0
word_freq_you                 0
word_freq_credit              0
word_freq_your                0
word_freq_font                0
word_freq_000                 0
word_freq_money               0
word_freq_hp                  0
word_freq_hpl                 0
word_freq_george              0
word_freq_650                 0
word_freq_lab                 0
word_freq_labs                0
word_freq_telnet              0
word_fre

In [7]:
df['class'].unique()

array([1, 0])

In [9]:
df.shape

(4601, 58)

# test and train data Split

In [11]:
Y = df['class']
X = df.drop('class', axis = 1)

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y, test_size = 0.33, random_state = 100)

In [13]:
x_train.head()

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,word_freq_conference,char_freq_%3B,char_freq_%28,char_freq_%5B,char_freq_%21,char_freq_%24,char_freq_%23,capital_run_length_average,capital_run_length_longest,capital_run_length_total
3610,0.0,0.0,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,...,0.0,0.0,0.000,0.0,0.00,0.0,0.0,1.000,1,5
1616,0.0,0.0,0.58,0.0,1.16,0.00,0.00,0.0,0.00,0.58,...,0.0,0.0,0.000,0.0,0.00,0.0,0.0,2.101,11,145
1453,0.0,0.0,0.28,0.0,0.84,0.84,0.28,0.0,0.28,0.28,...,0.0,0.0,0.050,0.0,0.05,0.0,0.0,2.083,34,150
4504,0.0,0.0,0.64,0.0,0.00,0.00,0.00,0.0,0.00,0.00,...,0.0,0.0,0.348,0.0,1.16,0.0,0.0,3.121,15,103
2495,0.0,0.0,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.00,...,0.0,0.0,0.000,0.0,0.74,0.0,0.0,1.625,6,13


In [14]:
x_test.head()

,word_freq_make,word_freq_address,word_freq_all,word_freq_3d,word_freq_our,word_freq_over,word_freq_remove,word_freq_internet,word_freq_order,word_freq_mail,...,word_freq_conference,char_freq_%3B,char_freq_%28,char_freq_%5B,char_freq_%21,char_freq_%24,char_freq_%23,capital_run_length_average,capital_run_length_longest,capital_run_length_total
2517,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.77,0.0,0.00,...,0.0,0.0,0.198,0.000,0.099,0.0,0.0,2.325,30,93
1557,0.0,1.63,0.81,0.0,0.00,0.00,1.63,0.00,0.0,1.63,...,0.0,0.0,0.000,0.000,1.212,0.0,0.0,15.916,71,191
4306,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,...,0.0,0.0,0.000,0.000,0.000,0.0,0.0,1.000,1,12
718,0.0,0.00,0.00,0.0,0.38,0.38,0.38,0.38,0.0,0.00,...,0.0,0.0,0.000,0.000,0.122,0.0,0.0,2.080,12,104
2158,0.0,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,...,0.0,0.0,0.000,0.222,0.000,0.0,0.0,5.357,28,150


In [15]:
y_train.head()

3610    0
1616    1
1453    1
4504    0
2495    0
Name: class, dtype: int64

In [16]:
y_test.head()

2517    0
1557    1
4306    0
718     1
2158    0
Name: class, dtype: int64

In [20]:
# doing standard scaling to assign proper weighatge for the values

In [22]:
# feature scalling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [23]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(x_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [28]:
y_pred = model.predict(x_test)
y_pred[0:10]

array([0, 1, 0, 1, 0, 1, 1, 0, 1, 0])

In [30]:
for i in (y_pred[0:10]):
    if y_pred[i] == 1:
        print('It is spam ')
    else :
        print('it is not a spam')

it is not a spam
It is spam 
it is not a spam
It is spam 
it is not a spam
It is spam 
It is spam 
it is not a spam
It is spam 
it is not a spam


In [34]:
y_pred[0:100]

array([0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0])

In [35]:
# evaluating the model using model evaluation metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9157340355497038

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.95      0.93       891
           1       0.92      0.87      0.90       628

    accuracy                           0.92      1519
   macro avg       0.92      0.91      0.91      1519
weighted avg       0.92      0.92      0.92      1519


Confusion Matrix:
[[842  49]
 [ 79 549]]


In [36]:
# trying other model to verfiy wheather we get better results or not
# in next step we are using a better model like decision tree
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(x_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [37]:
dt_pred = dt_model.predict(x_test)

In [38]:
dt_pred[0:50]

array([0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0])

In [39]:
# evaluating the model using model evaluation metrics
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, dt_pred))

print("\nClassification Report:")
print(classification_report(y_test, dt_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, dt_pred))

Accuracy: 0.913100724160632

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.92      0.93       891
           1       0.89      0.90      0.90       628

    accuracy                           0.91      1519
   macro avg       0.91      0.91      0.91      1519
weighted avg       0.91      0.91      0.91      1519


Confusion Matrix:
[[822  69]
 [ 63 565]]
